name: Deploy ASP.NET MVC App to Azure Web App

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: 'CICDDemoBymishranilu08'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    # Install NuGet
    - name: Install NuGet
      uses: nuget/setup-nuget@v2

    # Restore packages
    - name: Restore NuGet Packages
      run: nuget restore WebAppForCICD.sln

    # Add MSBuild
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    # Build & create ZIP
    - name: Build & Package
      run: |
        msbuild .\WebAppForCICD.sln `
          /p:Configuration=Release `
          /p:WebPublishMethod=Package `
          /p:PackageAsSingleFile=true `
          /p:SkipInvalidConfigurations=true `
          /p:PackageLocation="${{ github.workspace }}\WebAppForCICD.zip"

    # Verify ZIP exists
    - name: Verify ZIP
      run: |
        if (-Not (Test-Path "${{ github.workspace }}\WebAppForCICD.zip")) {
          Write-Error "ZIP file not found!"
        }

    # Upload ZIP artifact
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: published_app
        path: ${{ github.workspace }}\WebAppForCICD.zip

    # Deploy to Azure
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ github.workspace }}\WebAppForCICD.zip
