name: Deploy ASP.NET MVC App to Azure Web App

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: 'CICDDemoBymishranilu08'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    # Install NuGet
    - name: Install NuGet
      uses: nuget/setup-nuget@v2

    - name: Restore NuGet packages
      run: nuget restore WebAppForCICD.sln

    # Setup MSBuild
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1

    # Build and Publish
    - name: Build MVC and Publish
      run: |
        msbuild WebAppForCICD.sln ^
          /p:Configuration=Release ^
          /p:WebPublishMethod=FileSystem ^
          /p:PublishDir="${{ github.workspace }}\publish"

    # Check publish folder
    - name: Verify publish folder
      run: dir "${{ github.workspace }}\publish"

    # Upload artifact (v4)
    - name: Upload Published Artifact
      uses: actions/upload-artifact@v4
      with:
        name: published_app
        path: ${{ github.workspace }}\publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    # Download artifact
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: published_app
        path: ./publish

    # Deploy to Azure Web App
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish
